### PR TITLE
Desktop: Show modal for Ledger udev errors

### LINKED ISSUE #589: Can't get passed the "choose your ledger account index"
### Bug description
Can't get passed the "choose your ledger account index". Clicking continue does nothing.
Ledger is definitely recognized as soon as I plug it in and enter the pass code.
Ledger works with Ledger Live although I need to sudo to get to interact with the Ledger wallet. Trying  to run Trinity with sudo doesn't work: it lets me know I need to install dependencies that are already installed....
How to get a log???

### Environment Specs
- Manufacturer: Google
- Model: Pixelbook
- OS version: Ubuntu 18.04
- Trinity version: 0.4.1

### PR DESCRIPTION
**Pull request by rajivshah3**
# Description

Shows modal with a link to a Ledger [support article](https://support.ledger.com/hc/articles/115005165269) with details to help fix `udev` issues (see https://github.com/LedgerHQ/ledger-live-desktop/issues/1057)

image

Fixes #589 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

# How Has This Been Tested?

- Tested on Ubuntu 18.10 (dev)

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by cvarley100** [comment]
@rajivshah3 Do we need to add some form of navigational button i.e. `back`/`close`?

**Comment by rajivshah3** [comment]
@cvarley100 I can add it, but the steps require logging in/out and reconnecting the Ledger so Trinity will be restarted anyway

Edit: Once Rihards gets back I'll ask him for help adding this to the link whitelist so that users can simply click on it, so this screen might get replaced anyway.

**Review by cvarley100 — APPROVED** [review]

**Comment by cvarley100** [comment]
Do the strings need localisation?

**Comment by rajivshah3** [comment]
Whoops, forgot about that. Will add in a bit

**Review by rihardsgravis — APPROVED** [review]

**Pull request merged**
