### PR TITLE
Realm migrations setup improvements

### LINKED ISSUE #1162: Improve Realm migration setup
### Description
Improve realm schema migration setup. Preferably use [linear-migrations](https://realm.io/docs/javascript/latest/#linear-migrations).

### Motivation
The current realm migration setup is very limiting and only support migration from schema version `0` to `1`. It will fail if new properties are added/removed from the defined schemas. 

### Requirements

- Migration setup should work seamlessly for multiple schema versions. 
- Migration setup should be improved to a level where the only requirement to migrate is to define a new migration function.

### Am I planning to do it myself with a PR?
Yes.

### PR DESCRIPTION
**Pull request by laumair**
# Description

Fixes https://github.com/iotaledger/trinity-wallet/issues/1162

## Type of change

- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?

- Manually tested
- Unit tests update

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] For changes to `mobile` that include native code (including React Native modules): I have verified that both iOS and Android successfully build in both `Debug` and `Release` modes
- [ ] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

### CODE REVIEW

**Comment by rajivshah3** [comment]
Not sure if this is intentional or a bug:

If I start with a fresh simulator, run Trinity on the `develop` branch, and complete the onboarding, the Documents directory looks like this (run `open $(xcrun simctl get_app_container booted com.iota.trinity data)/Documents` to open it): 
image

Then, I checkout `feat/realm-migrations` and run the app again. When I reach the login screen, it looks like this:
image

If I don't log in, but simply run the app again, it looks like `trinity-1` is recreated:
image

**Comment by laumair** [comment]
> If I don't log in, but simply run the app again, it looks like trinity-1 is recreated:

On which branch are you facing this?

**Comment by laumair** [comment]
This PR changes the storage path for realm but it should also remove the realm files on old paths.

**Comment by rajivshah3** [comment]
> On which branch are you facing this?

I think this one

**Comment by laumair** [comment]
@rajivshah3 I'll investigate.

**Review by cvarley100 — APPROVED** [review]

**Comment by cvarley100** [comment]
@laumair Perhaps we should add some documentation on how to write a migration, and which variables need updating?

**Review by rajivshah3 — APPROVED** [review]
Looks good. Could you reset the changes to the shrinkwrap? It looks like there weren't any changes to `desktop/package.json` so I don't think changes to the shrinkwrap are necessary

**Comment by laumair** [comment]
@rajivshah3 

> Looks good. Could you reset the changes to the shrinkwrap? It looks like there weren't any changes to desktop/package.json so I don't think changes to the shrinkwrap are necessary

[Done](https://github.com/iotaledger/trinity-wallet/pull/1168/commits/17c2fa73c288afb425e14f8c8fa79ecb9c51cfe1)

**Comment by laumair** [comment]
@cvarley100 

> Perhaps we should add some documentation on how to write a migration, and which variables need updating?

Good idea. I've created an [issue](https://github.com/iotaledger/trinity-wallet/issues/1267). Will do a separate PR for this.

**Pull request merged**
