### PR TITLE
#508 Increasing margin of inner div to be able to show all characters…

### LINKED ISSUE #508: Seed's first 2 letters will disappear if go back with left arrow
### Bug description
Seed display will disappear if go back with left arrow

### Environment Specs
- OS version: windows 7.0 pro
- Trinity version: v0.3.6 Beta

### Steps To Reproduce
1. Add a new account with existing seed
2. clic on the eye to see the letters you enter
3. Type enough letters to empty the display and at least one more
4. Go back to the left with left arrow.

### Expected behaviour
When you try to enter your seed to create a new account :
Everything is OK till the seed doesn't fill the all display :
[Image](https://goopics.net/i/nd07K)
As soon as the seed is too long for the display, we can see the left part of the seed disappear :
[Image](https://goopics.net/i/Xg1YX)
nothing strange till here...
But then, if we move the cursor back to the left (with left arrow), the seed should reappear...

### Actual behaviour
The seed reappears for a few letters but not till the beggining of the seed, so the cursor also disappear on the left part of the display :
[Image](https://goopics.net/i/PnyY0)
That's a bit disturbing when you want to check your seed before validation.

### PR DESCRIPTION
**Pull request by delki8**
Fixes https://github.com/iotaledger/trinity-wallet/issues/508

## Type of change
- Bug fix (a non-breaking change which fixes an issue)

# How Has This Been Tested?
Following the steps in the original issue and stating that when the user types more characters than the size of the field he'll be able to go back with the left arrow and see all of the typed characters.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by laumair** [comment]
@delki8 I updated PR description to reference the related issue.

**Comment by delki8** [comment]
> @delki8 I updated PR description to reference the related issue.

No problem @laumair and ty.

**Comment by laumair** [comment]
@rihardsgravis Awaiting your reviews!

**Comment by cvarley100** [comment]
@delki8 This PR is now 2 months old, we really should get it merged. 

Could you give some alternative instructions on how to reproduce the bug mentioned in #508? We have followed the above instructions and can't repro the issue, so we're not actually sure what this PR fixes.

**Comment by rajivshah3** [comment]
@cvarley100 I remember being able to reproduce the issue a while ago, but I’m not entirely sure whether this PR fixes the issue as it seems the root cause is somewhere else. I’ll see if I can get a screen recording

**Comment by laumair** [comment]
@rajivshah3 Were you able to reproduce the issue?

**Comment by rajivshah3** [comment]
@laumair I tried a few weeks ago and I don't think I was able to reproduce it on RC2. I left a comment on #508 but I'll ask if this is still reproducible on the latest version

**Comment by laumair** [comment]
@rajivshah3 Thanks for the update. Can we perhaps close this for now and reopen when this is reproducible?

**Comment by rajivshah3** [comment]
@delki8 are you able to reproduce this on the latest version? If not then we can probably close this

**Comment by laumair** [comment]
Closing due to inactivity. Please reopen when this is reproducible.

**Pull request closed without merging**
