### PR TITLE
Adding Night, Changes to Dark, and editing themes

### LINKED ISSUE #1959: Dark theme needs refinement
### Bug description
The borders of input fields on dark theme are very bright and aren't using the values from the theme javascript. Instead of using opacity, the app displays white borders. It should be #666666 but displays as white instead

### Environment Specs
What device are you running Trinity on?
Android Moto Z3 64gb. I will unfortunately be unable to recreate this until tomorrow when I'll be checking it on a Moto Z4. 

- Manufacturer: Motorola 
- Model: Z3
- OS version: Android 9 Pie

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version:

Current Version
1.0.0

### Steps To Reproduce
1. Switch to dark theme

### Expected behaviour
Using code from the theme: rgba(255, 255, 255, 0.4)"
Should display as gray/grey against black background. 

### Actual behaviour
Displays as white

Note: I will also check this against the Linux version soon. Consider using values without alpha.

### PR DESCRIPTION
**Pull request by MatthewScheuerman**
# Description
Because there were several screens and inputs that were too bright and created too high of contrast to the eyes at night, I have created an updated version of Dark mode that fixes some of these issues and I've added a Night mode that is even darker.

Fixes #1959

## Type of change
- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?
Enhancement (a non-breaking change which adds functionality)

How Has This Been Tested?
I've provided screenshots in the issue ticket and I've tested this on desktop several times

# Checklist:

_Please delete items that are not relevant._

- [x] My code follows the style guidelines for this project

NOTE: I am working on a fork of the IOTA-CSS-Theme and working on finding values for that fork so that led me to look into the themes for Trinity.

- [x] I have performed a self-review of my own code
- [ ] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

I was not able to test mobile.

### CODE REVIEW

**Comment by rihardsgravis** [comment]
@MatthewScheuerman please, add `Night` theme name also to the translatable strings at this file - https://github.com/iotaledger/trinity-wallet/blob/209ad83b30bdea08c41e97401188dde0c1e41b56/src/shared/locales/en/translation.json#L556

**Comment by andrew-brough** [comment]
Happy with the new theme proposal. Suggest that we retain the white text for notifications, instead of changing it to black (on red or green background). The consensus is that it is more legible. 

The limited frequency of visibility reduces it as a source of harsh light for night-time users.

**Comment by MatthewScheuerman** [comment]
@rihardsgravis Will do. Thanks!
@andrew-brough Thanks for letting me know about the consensus on that. I'll change it back. Much appreciated!

Is this a design system decision that will be reflected across other projects/products? Just curious.

**Comment by rihardsgravis** [comment]
@MatthewScheuerman considering that `Dark` and `Night` themes have very little variation, we suggest to stick with the `Night` theme only and `Dark` could now be removed from the codebase. What do you think?

**Comment by MatthewScheuerman** [comment]
@rihardsgravis I'm totally fine with that. Do you think that `Night` should be renamed `Dark` (keeping the `Night` theme code...copying it over to `Dark`) and just remove Night completely?

I asked about what people preferred visually, on twitter, and it was unfortunately very 50/50. 
https://twitter.com/mordecaidesign/status/1149652566130561025

**Review by rihardsgravis — APPROVED** [review]

**Comment by rihardsgravis** [comment]
Thank you @MatthewScheuerman for caring about the details and this PR!

**Comment by MatthewScheuerman** [comment]
@rihardsgravis @rajivshah3 @andrew-brough Thank you for letting me make this pull request and take part in this. Looking forward to doing more in the future.

**Pull request merged**
