### PR TITLE
Desktop: Add `ignoreProxy` setting to Realm

### LINKED ISSUE #1683: Use system proxy setting doesn't get saved
### Bug description
After I disabled `Use system proxy` I restarted Trinity and after starting it again it says `Enabled` again.

### Environment Specs

- OS version: Windows 10 1809
- Trinity version: 0.6.0-RC1

### Steps To Reproduce
1. open advanced settings
2. disable `Use system proxy`
3. restart Trinity

### Expected behaviour
should still be disabled

### Actual behaviour
is enabled again

### PR DESCRIPTION
**Pull request by rihardsgravis**
# Description

State `settings.ignoreProxy` is missing in Realm.

Fixes #1683 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

# How Has This Been Tested?

macOS

# Checklist:

- [x] My code follows the style guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] For changes to `mobile` that include native code (including React Native modules): I have verified that both iOS and Android successfully build in both `Debug` and `Release` modes
- [ ] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

### CODE REVIEW

**Comment by rihardsgravis** [comment]
@laumair could you, please, review and add missing changes? I added the missing Realm hook, but seems like more changes are required as it's not saving the state.

**Comment by laumair** [comment]
@rihardsgravis I'll work on this.

**Comment by laumair** [comment]
I'll do it once https://github.com/iotaledger/trinity-wallet/pulls is merged as it has some schema updates already.

**Comment by laumair** [comment]
@rihardsgravis https://github.com/iotaledger/trinity-wallet/pull/1730

**Review by laumair — APPROVED** [review]
LGTM! 💯

**Pull request merged**
